name: gid

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      command_type:
        description: 'command type to control flow'
        required: true
        type: choice
        options:
        - plan

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Digger Action
        id: digger
        uses: ./.github/actions/orchestrate
        with:
          path-to-tf-project: '.'
          event_payload: ${{ toJson(github.event) }}
          event_name: ${{ github.event_name }}
